# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-3.0-or-later
version = 1
SPDX-PackageName = "Android-SingleSignOn"
SPDX-PackageSupplier = "Nextcloud Android team <android@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/Android-SingleSignOn"

[[annotations]]
path = ["gradle/wrapper/gradle-wrapper.jar", "sample_client/gradle/wrapper/gradle-wrapper.jar"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2021 the original authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["gradle/verification-keyring.keys", "gradle/verification-metadata.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["renovate.json5", "**/.gitignore", ".idea/**", "scripts/analysis/findbugs-results.txt", "scripts/analysis/lint-results.txt", "sample/src/main/res/mipmap-**dpi/ic_launcher.webp", "sample/src/main/res/mipmap-**dpi/ic_launcher_round.webp"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
