 * SPDX-FileCopyrightText: 2020-2024 Nextcloud GmbH and Nextcloud contributors
 * SPDX-FileCopyrightText: 2020 Tobias Kaminsky <tobias@kaminsky.me>
 * SPDX-License-Identifier: GPL-3.0-or-later
name: Dependabot
on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # Default github action approve
      - uses: hmarr/auto-approve-action@v4.0.0
        if: github.ref == 'refs/heads/master' &&
          (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Nextcloud bot approve and merge request
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        if: github.ref == 'refs/heads/master' &&
          (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
